### ISSUE TITLE
Feature Request: gnus-registry-marks; Is it possible to use for narrowing, searching 

### ISSUE THREAD

**Issue by poulpoulsen** [deusmax/gnus-notes#6] opened 2020-08-29 19:39 UTC
Hello,
after some usage of your package i remember an old idea.
i want to search or filter with the registry-marks i set. Is this
possible with your package? I couldn't find a function in gnus manual for that.

Regards
Poul

**Comment by deusmax** [comment] 2020-08-29 23:46
Hi Poul,

Thanks, that is a good idea.
I also thought of adding org style tags to gnus-notes, which may be a similar concept to registry-marks.
I gave-up on using the gnus-registry because all my attempts end-up with troubles. Maybe it was just my bad luck.
So, my short answer to your question is No, this package currently does not integrate with gnus-registry.
 
My current thinking is that org-mode is far better for keeping track of todo states and handling tags.
Org-mode excels at keeping track of actions, scheduling, tag filtering and all the other stuff.
There is little gain in trying to replicate this functionality in gnus. It may actually result in a regression, by making things harder and more complicated.

Here is an example of what I mean:
So for email, when I want to have an action, a todo heading is created. For instance, to reply to an email at work, an org-entry like the one below may be used:
* **REPLY** Update boss on project ABC next steps                                                   :boss:othertag:
  **DEADLINE**: <2020-09-03 Thu> 
   - [2020-08-27 Thu 16:12]  [email from Boss Name: Update on ABC next]
     Here I can add some useful comments to myself.

You may recognize the list entry as a quick-note action (currently <F6>) from gnus-notes.
After replying, the task can be closed with:
1. the keyword will be changed from REPLY to REPLIED.
2. a CLOSED entry will be added by org-mode.
3. another quick-note with the email-sent timestamp and gnus-link will be added, with perhaps some additional comments.

Now I have he whole history on this email exchange (or thread) nicely summarized in one place. My (pending) actions are nicely reviewable on my org Agenda, etc. !

**Comment by deusmax** [comment] 2020-09-01 17:39
Gnus-registry marks are like tags, but without any additional functionality.
One can add marks to articles in gnus-registry for display purposes only. No search or filtering, if I'm correct.

Closing this issue.

**Closed as completed by deusmax** 2020-09-01 17:39 UTC
